# Generated by Django 4.1 on 2022-08-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematics',
            name='category',
            field=models.CharField(choices=[('redstone', 'Redstone'), ('build', 'Build'), ('misc', 'Miscellaneous')], default='misc', max_length=8),
        ),
        migrations.AddField(
            model_name='schematics',
            name='shortDescription',
            field=models.CharField(default='OLD DESC', help_text='A short description for showing in the lists', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schematics',
            name='source',
            field=models.CharField(default='ME', help_text='The source for the schematic', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schematics',
            name='description',
            field=models.CharField(help_text='The actual description shown in the dedicated page for the schematic', max_length=1024),
        ),
        migrations.AlterField(
            model_name='schematics',
            name='image',
            field=models.CharField(help_text='link to the image for the schematic thumbnail', max_length=1024),
        ),
        migrations.AlterField(
            model_name='schematics',
            name='keyWords',
            field=models.CharField(help_text='Key words for finding the schematic', max_length=255),
        ),
        migrations.AlterField(
            model_name='schematics',
            name='title',
            field=models.CharField(help_text='Title for the schematic', max_length=255),
        ),
    ]
