# Generated by Django 4.1 on 2022-08-27 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0002_schematics_category_schematics_shortdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematics',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
