# Generated by Django 4.1 on 2022-08-28 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0005_schematics_currentdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schematics',
            name='currentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 11, 19, 52, 267883, tzinfo=datetime.timezone.utc)),
        ),
    ]
