# Generated by Django 4.1 on 2022-08-28 19:30

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0009_schematics_uniquerandomurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schematics',
            name='uniqueRandomURL',
        ),
        migrations.AlterField(
            model_name='schematics',
            name='currentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 19, 30, 21, 599169, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='schematics',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
