# Generated by Django 4.1 on 2022-08-28 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0010_remove_schematics_uniquerandomurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schematics',
            name='currentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 19, 41, 14, 3366, tzinfo=datetime.timezone.utc)),
        ),
    ]
