# Generated by Django 4.1 on 2022-08-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0015_categoryselect_remove_schematics_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schematics',
            name='description',
            field=models.CharField(help_text='The actual description shown in the dedicated page for the schematic', max_length=100000),
        ),
    ]
