# Generated by Django 4.1 on 2022-08-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0017_remove_schematics_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematics',
            name='downloadCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
