# Generated by Django 4.1 on 2022-08-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0019_schematics_downloadcounthr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schematics',
            name='source',
        ),
        migrations.AddField(
            model_name='schematics',
            name='sourceLink',
            field=models.CharField(default='example.com/source', help_text='The source for the downloaded map/downloaded schematic', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schematics',
            name='sourceType',
            field=models.CharField(choices=[('downloadedMap', 'Downloaded map and created schematic'), ('downlodedSchematic', 'Downloaded schematic directly')], default='downloadedSchematic', max_length=20),
        ),
    ]
